import 'dart:math';

/// Servicio centralizado para generar nombres de pilotos con alta variedad.
///
/// Provee listas extensas de nombres y apellidos diferenciados por país,
/// con lógica anti-repetición para evitar duplicados en el mismo contexto.
class DriverNameService {
  final Random _random;

  /// Nombres ya usados en esta sesión de generación (por contexto)
  final Set<String> _usedNames = {};

  DriverNameService({Random? random}) : _random = random ?? Random();

  /// Limpia el registro de nombres usados (útil al iniciar un nuevo seeding)
  void resetUsedNames() => _usedNames.clear();

  /// Genera un nombre completo único para un piloto dado su género y país.
  ///
  /// Intenta hasta [maxAttempts] veces generar un nombre no repetido.
  /// Si no lo logra, devuelve el último generado (para evitar bucles infinitos).
  String generateName({
    required String gender,
    required String countryCode,
    int maxAttempts = 10,
  }) {
    String name = '';
    for (int i = 0; i < maxAttempts; i++) {
      name = _buildName(gender: gender, countryCode: countryCode);
      if (!_usedNames.contains(name)) {
        _usedNames.add(name);
        return name;
      }
    }
    // Si agotamos intentos, registramos igual y devolvemos
    _usedNames.add(name);
    return name;
  }

  String _buildName({required String gender, required String countryCode}) {
    final firstNames = gender == 'M'
        ? (_maleFirstNames[countryCode] ?? _defaultMaleNames)
        : (_femaleFirstNames[countryCode] ?? _defaultFemaleNames);
    final lastNames = _lastNames[countryCode] ?? _defaultLastNames;

    final first = firstNames[_random.nextInt(firstNames.length)];

    // 30% de probabilidad de usar dos apellidos para mayor variedad
    final String last;
    if (_random.nextInt(100) < 30 && lastNames.length >= 2) {
      final idx1 = _random.nextInt(lastNames.length);
      int idx2 = _random.nextInt(lastNames.length);
      while (idx2 == idx1) {
        idx2 = _random.nextInt(lastNames.length);
      }
      last = '${lastNames[idx1]} ${lastNames[idx2]}';
    } else {
      last = lastNames[_random.nextInt(lastNames.length)];
    }

    return '$first $last';
  }

  // ─── Nombres masculinos por país ──────────────────────────────────────────

  static const Map<String, List<String>> _maleFirstNames = {
    'BR': [
      'Lucas',
      'Gabriel',
      'João',
      'Miguel',
      'Pedro',
      'Rafael',
      'Mateus',
      'Guilherme',
      'Felipe',
      'Bruno',
      'Thiago',
      'Eduardo',
      'Rodrigo',
      'André',
      'Leandro',
      'Marcelo',
      'Vinícius',
      'Caio',
      'Gustavo',
      'Henrique',
      'Leonardo',
      'Murilo',
      'Otávio',
      'Renato',
      'Sandro',
      'Tiago',
      'Yago',
      'Davi',
      'Enzo',
      'Cauã',
    ],
    'AR': [
      'Mateo',
      'Santiago',
      'Diego',
      'Benjamín',
      'Nicolás',
      'Agustín',
      'Facundo',
      'Ignacio',
      'Tomás',
      'Martín',
      'Ezequiel',
      'Rodrigo',
      'Maximiliano',
      'Leandro',
      'Gonzalo',
      'Hernán',
      'Cristian',
      'Damián',
      'Emiliano',
      'Federico',
      'Gastón',
      'Javier',
      'Luciano',
      'Marcos',
      'Pablo',
      'Ramiro',
      'Sebastián',
      'Valentín',
      'Walter',
      'Alexis',
    ],
    'CO': [
      'Matías',
      'Samuel',
      'Andrés',
      'Sebastián',
      'David',
      'Daniel',
      'Camilo',
      'Felipe',
      'Juan',
      'Carlos',
      'Alejandro',
      'Esteban',
      'Nicolás',
      'Julián',
      'Sergio',
      'Ricardo',
      'Mauricio',
      'Cristóbal',
      'Iván',
      'Óscar',
      'Jhon',
      'Brayan',
      'Stiven',
      'Javier',
      'Luis',
      'Édgar',
      'Fabio',
      'Germán',
      'Harold',
      'Wilmar',
    ],
    'MX': [
      'Miguel',
      'Diego',
      'Alejandro',
      'Carlos',
      'Emilio',
      'Fernando',
      'Rodrigo',
      'Adrián',
      'Ángel',
      'Armando',
      'César',
      'Eduardo',
      'Ernesto',
      'Francisco',
      'Gerardo',
      'Hugo',
      'Iván',
      'Jorge',
      'José',
      'Juan',
      'Luis',
      'Manuel',
      'Mauricio',
      'Omar',
      'Pablo',
      'Rafael',
      'Raúl',
      'Roberto',
      'Salvador',
      'Víctor',
    ],
    'UY': [
      'Joaquín',
      'Mateo',
      'Nicolás',
      'Felipe',
      'Agustín',
      'Sebastián',
      'Facundo',
      'Ignacio',
      'Tomás',
      'Martín',
      'Andrés',
      'Bruno',
      'Camilo',
      'Diego',
      'Emiliano',
      'Federico',
      'Gastón',
      'Hernán',
      'Leandro',
      'Marcos',
      'Pablo',
      'Rodrigo',
      'Santiago',
      'Valentín',
      'Álvaro',
      'Cristian',
      'Damián',
      'Ezequiel',
      'Gonzalo',
      'Ramiro',
    ],
    'CL': [
      'Matías',
      'Benjamín',
      'Vicente',
      'Agustín',
      'Sebastián',
      'Nicolás',
      'Ignacio',
      'Tomás',
      'Felipe',
      'Diego',
      'Andrés',
      'Camilo',
      'Cristóbal',
      'Emilio',
      'Esteban',
      'Fabián',
      'Gabriel',
      'Gonzalo',
      'Héctor',
      'Javier',
      'Jorge',
      'Leonardo',
      'Marcelo',
      'Mauricio',
      'Patricio',
      'Rodrigo',
      'Sergio',
      'Simón',
      'Víctor',
      'Yerko',
    ],
  };

  // ─── Nombres femeninos por país ───────────────────────────────────────────

  static const Map<String, List<String>> _femaleFirstNames = {
    'BR': [
      'Sofia',
      'Maria',
      'Ana',
      'Isabela',
      'Beatriz',
      'Larissa',
      'Fernanda',
      'Juliana',
      'Camila',
      'Letícia',
      'Aline',
      'Bruna',
      'Carolina',
      'Débora',
      'Elisa',
      'Flávia',
      'Gabriela',
      'Helena',
      'Isadora',
      'Jéssica',
      'Karina',
      'Luana',
      'Mariana',
      'Natália',
      'Priscila',
      'Renata',
      'Sabrina',
      'Thaís',
      'Vanessa',
      'Yasmin',
    ],
    'AR': [
      'Valentina',
      'Emma',
      'Lucía',
      'Martina',
      'Sofía',
      'Camila',
      'Isabella',
      'Florencia',
      'Agustina',
      'Milagros',
      'Rocío',
      'Julieta',
      'Antonella',
      'Bianca',
      'Celeste',
      'Daniela',
      'Eugenia',
      'Fernanda',
      'Gisela',
      'Hernanda',
      'Ivana',
      'Jimena',
      'Karina',
      'Laura',
      'Melina',
      'Natalia',
      'Paula',
      'Romina',
      'Silvina',
      'Tamara',
    ],
    'CO': [
      'Isabella',
      'Catalina',
      'Camila',
      'Valeria',
      'Valentina',
      'Sara',
      'Daniela',
      'Mariana',
      'Natalia',
      'Alejandra',
      'Andrea',
      'Ángela',
      'Bibiana',
      'Carolina',
      'Diana',
      'Eliana',
      'Fernanda',
      'Gloria',
      'Juliana',
      'Karen',
      'Leidy',
      'Marcela',
      'Nathalia',
      'Paola',
      'Tatiana',
      'Vanessa',
      'Xiomara',
      'Yesenia',
      'Zulma',
      'Adriana',
    ],
    'MX': [
      'Sofía',
      'Valentina',
      'Regina',
      'Fernanda',
      'Camila',
      'Mariana',
      'Daniela',
      'Lucía',
      'Valeria',
      'Isabella',
      'Adriana',
      'Alejandra',
      'Brenda',
      'Claudia',
      'Diana',
      'Estefanía',
      'Gabriela',
      'Itzel',
      'Jimena',
      'Karen',
      'Lorena',
      'Montserrat',
      'Natalia',
      'Paola',
      'Rebeca',
      'Sandra',
      'Tania',
      'Verónica',
      'Wendy',
      'Ximena',
    ],
    'UY': [
      'Martina',
      'Sofía',
      'Valentina',
      'Emma',
      'Lucía',
      'Camila',
      'Florencia',
      'Agustina',
      'Milagros',
      'Rocío',
      'Antonella',
      'Bianca',
      'Celeste',
      'Daniela',
      'Eugenia',
      'Fernanda',
      'Gisela',
      'Ivana',
      'Jimena',
      'Karina',
      'Laura',
      'Melina',
      'Natalia',
      'Paula',
      'Romina',
      'Silvina',
      'Tamara',
      'Verónica',
      'Ximena',
      'Yanina',
    ],
    'CL': [
      'Sofía',
      'Florencia',
      'Isidora',
      'Emilia',
      'Valentina',
      'Camila',
      'Catalina',
      'Martina',
      'Antonia',
      'Javiera',
      'Alejandra',
      'Bárbara',
      'Constanza',
      'Daniela',
      'Francisca',
      'Gabriela',
      'Ignacia',
      'Josefa',
      'Karina',
      'Lorena',
      'Macarena',
      'Natalia',
      'Paola',
      'Rocío',
      'Soledad',
      'Trinidad',
      'Valentina',
      'Ximena',
      'Yasna',
      'Zoraya',
    ],
  };

  // ─── Apellidos por país ───────────────────────────────────────────────────

  static const Map<String, List<String>> _lastNames = {
    'BR': [
      'Silva',
      'Santos',
      'Oliveira',
      'Souza',
      'Costa',
      'Ferreira',
      'Rodrigues',
      'Almeida',
      'Nascimento',
      'Lima',
      'Araújo',
      'Fernandes',
      'Carvalho',
      'Gomes',
      'Martins',
      'Rocha',
      'Ribeiro',
      'Alves',
      'Monteiro',
      'Mendes',
      'Barros',
      'Freitas',
      'Barbosa',
      'Pinto',
      'Moura',
      'Cavalcanti',
      'Dias',
      'Castro',
      'Correia',
      'Moreira',
      'Nunes',
      'Teixeira',
      'Vieira',
      'Cunha',
      'Peixoto',
      'Figueiredo',
      'Azevedo',
      'Cardoso',
      'Machado',
      'Ramos',
    ],
    'AR': [
      'González',
      'Rodríguez',
      'Fernández',
      'López',
      'Martínez',
      'García',
      'Pérez',
      'Sánchez',
      'Romero',
      'Sosa',
      'Torres',
      'Álvarez',
      'Ruiz',
      'Ramírez',
      'Flores',
      'Acosta',
      'Benítez',
      'Cabrera',
      'Díaz',
      'Herrera',
      'Medina',
      'Molina',
      'Morales',
      'Núñez',
      'Ortiz',
      'Ramos',
      'Reyes',
      'Ríos',
      'Vargas',
      'Vega',
      'Aguirre',
      'Blanco',
      'Bustos',
      'Castro',
      'Correa',
      'Delgado',
      'Escobar',
      'Figueroa',
      'Gutiérrez',
      'Ibáñez',
    ],
    'CO': [
      'García',
      'Rodríguez',
      'González',
      'Hernández',
      'López',
      'Martínez',
      'Torres',
      'Ramírez',
      'Gómez',
      'Vargas',
      'Moreno',
      'Jiménez',
      'Díaz',
      'Reyes',
      'Sánchez',
      'Castillo',
      'Ramos',
      'Peña',
      'Cruz',
      'Ríos',
      'Aguilar',
      'Álvarez',
      'Bernal',
      'Cárdenas',
      'Caro',
      'Cifuentes',
      'Duarte',
      'Escobar',
      'Flórez',
      'Guerrero',
      'Gutiérrez',
      'Herrera',
      'Lozano',
      'Medina',
      'Montoya',
      'Mora',
      'Muñoz',
      'Nieto',
      'Ospina',
      'Pardo',
    ],
    'MX': [
      'García',
      'Hernández',
      'López',
      'González',
      'Martínez',
      'Rodríguez',
      'Pérez',
      'Sánchez',
      'Ramírez',
      'Torres',
      'Flores',
      'Rivera',
      'Gómez',
      'Díaz',
      'Cruz',
      'Morales',
      'Reyes',
      'Gutiérrez',
      'Ortiz',
      'Chávez',
      'Ramos',
      'Herrera',
      'Jiménez',
      'Moreno',
      'Álvarez',
      'Romero',
      'Vargas',
      'Castillo',
      'Mendoza',
      'Ruiz',
      'Aguilar',
      'Medina',
      'Vega',
      'Ríos',
      'Acosta',
      'Delgado',
      'Espinoza',
      'Fuentes',
      'Guerrero',
      'Lara',
    ],
    'UY': [
      'González',
      'Rodríguez',
      'Fernández',
      'García',
      'López',
      'Martínez',
      'Pérez',
      'Sánchez',
      'Romero',
      'Sosa',
      'Torres',
      'Álvarez',
      'Ruiz',
      'Ramírez',
      'Flores',
      'Acosta',
      'Benítez',
      'Cabrera',
      'Díaz',
      'Herrera',
      'Medina',
      'Molina',
      'Morales',
      'Núñez',
      'Ortiz',
      'Ramos',
      'Reyes',
      'Ríos',
      'Vargas',
      'Vega',
      'Da Silva',
      'Pereira',
      'Suárez',
      'Bentancur',
      'Cavani',
      'Godín',
      'Lugano',
      'Muslera',
      'Recoba',
      'Tabárez',
    ],
    'CL': [
      'González',
      'Muñoz',
      'Rojas',
      'Díaz',
      'Pérez',
      'Soto',
      'Contreras',
      'Silva',
      'Martínez',
      'Sepúlveda',
      'Morales',
      'Rodríguez',
      'López',
      'Fuentes',
      'Hernández',
      'Torres',
      'Araya',
      'Flores',
      'Espinoza',
      'Valenzuela',
      'Castillo',
      'Ramírez',
      'Reyes',
      'Gutiérrez',
      'Castro',
      'Vargas',
      'Álvarez',
      'Vásquez',
      'Tapia',
      'Fernández',
      'Herrera',
      'Aguilera',
      'Bravo',
      'Cárdenas',
      'Cortés',
      'Figueroa',
      'Garrido',
      'Ibáñez',
      'Jara',
      'Leiva',
    ],
  };

  // ─── Defaults para países no mapeados ─────────────────────────────────────

  static const List<String> _defaultMaleNames = [
    'Alex',
    'Jordan',
    'Taylor',
    'Morgan',
    'Casey',
    'Riley',
    'Jamie',
    'Avery',
    'Quinn',
    'Blake',
    'Cameron',
    'Drew',
    'Elliot',
    'Finley',
    'Gray',
    'Harper',
    'Indigo',
    'Jesse',
    'Kendall',
    'Logan',
  ];

  static const List<String> _defaultFemaleNames = [
    'Alex',
    'Jordan',
    'Taylor',
    'Morgan',
    'Casey',
    'Riley',
    'Jamie',
    'Avery',
    'Quinn',
    'Blake',
    'Cameron',
    'Drew',
    'Elliot',
    'Finley',
    'Gray',
    'Harper',
    'Indigo',
    'Jesse',
    'Kendall',
    'Logan',
  ];

  static const List<String> _defaultLastNames = [
    'Smith',
    'Johnson',
    'Williams',
    'Brown',
    'Jones',
    'Garcia',
    'Miller',
    'Davis',
    'Wilson',
    'Taylor',
    'Anderson',
    'Thomas',
    'Jackson',
    'White',
    'Harris',
    'Martin',
    'Thompson',
    'Young',
    'Allen',
    'King',
  ];
}
