// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0RViQhIglCogFLtic-vL_9YgrXLezTZY',
    appId: '1:822361821036:web:54e166db008180e748ed49',
    messagingSenderId: '822361821036',
    projectId: 'ftg-racing-manager',
    authDomain: 'ftg-racing-manager.firebaseapp.com',
    storageBucket: 'ftg-racing-manager.firebasestorage.app',
    measurementId: 'G-2LGJG8KTF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABVXH5RRcZV8UgAS8oOC2XEC2fpUzuYpw',
    appId: '1:822361821036:android:ae317c8dd178d51848ed49',
    messagingSenderId: '822361821036',
    projectId: 'ftg-racing-manager',
    storageBucket: 'ftg-racing-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYkibJXmWhuZyER-1EcToqjG6305Jk2Qc',
    appId: '1:822361821036:ios:e69aae6344c6e24248ed49',
    messagingSenderId: '822361821036',
    projectId: 'ftg-racing-manager',
    storageBucket: 'ftg-racing-manager.firebasestorage.app',
    iosClientId: '822361821036-shp1s82ioam62qu6q23dictq6ep9j7u0.apps.googleusercontent.com',
    iosBundleId: 'com.firetower.racingmanager',
  );
}
